-- ========================================================
-- SMART FYP MANAGEMENT - FULL POSTGRESQL SCHEMA FOR NEON
-- Database: neondb (PostgreSQL)
-- ========================================================

CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

-- Migration: contenttypes - 0001_initial
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;


-- Migration: contenttypes - 0002_remove_content_type_name
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;
COMMIT;


-- Migration: auth - 0001_initial
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
COMMIT;


-- Migration: auth - 0002_alter_permission_name_max_length
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;


-- Migration: auth - 0003_alter_user_email_max_length
BEGIN;
--
-- Alter field email on user
--
-- (no-op)
COMMIT;


-- Migration: auth - 0004_alter_user_username_opts
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;


-- Migration: auth - 0005_alter_user_last_login_null
BEGIN;
--
-- Alter field last_login on user
--
-- (no-op)
COMMIT;


-- Migration: auth - 0007_alter_validators_add_error_messages
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;


-- Migration: auth - 0008_alter_user_username_max_length
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;


-- Migration: auth - 0009_alter_user_last_name_max_length
BEGIN;
--
-- Alter field last_name on user
--
-- (no-op)
COMMIT;


-- Migration: auth - 0010_alter_group_name_max_length
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;


-- Migration: auth - 0011_update_proxy_permissions
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;


-- Migration: auth - 0012_alter_user_first_name_max_length
BEGIN;
--
-- Alter field first_name on user
--
-- (no-op)
COMMIT;


-- Migration: app - 0001_initial
BEGIN;
--
-- Create model CustomUser
--
CREATE TABLE "app_customuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "user_type" varchar(50) NOT NULL);
CREATE TABLE "app_customuser_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "customuser_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "app_customuser_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "customuser_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model CommitteeMember
--
CREATE TABLE "app_committeemember" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "committee_id" varchar(100) NOT NULL UNIQUE);
--
-- Create model CommitteeMemberPanel
--
CREATE TABLE "app_committeememberpanel" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NULL);
--
-- Create model Document
--
CREATE TABLE "app_document" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "document_type" varchar(50) NOT NULL, "status" varchar(20) NOT NULL, "title" varchar(100) NOT NULL, "uploaded_file" varchar(100) NOT NULL, "uploaded_at" timestamp with time zone NOT NULL);
--
-- Create model Evaluation3CommitteeMember
--
CREATE TABLE "app_evaluation3committeemember" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "module_completion" varchar(15) NOT NULL, "software_testing" varchar(15) NOT NULL, "qa_ability" varchar(15) NOT NULL, "proper_attire" varchar(15) NOT NULL, "is_template_followed" varchar(15) NOT NULL, "is_writeup_correct" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model Evaluation3Supervisor
--
CREATE TABLE "app_evaluation3supervisor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "module_completion" varchar(15) NOT NULL, "software_testing" varchar(15) NOT NULL, "regularity" varchar(15) NOT NULL, "is_template_followed" varchar(15) NOT NULL, "project_domain_knowledge" varchar(15) NOT NULL, "is_writeup_correct" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model Evaluation4CommitteeMember
--
CREATE TABLE "app_evaluation4committeemember" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "module_completion" varchar(15) NOT NULL, "software_testing" varchar(15) NOT NULL, "qa_ability" varchar(15) NOT NULL, "proper_attire" varchar(15) NOT NULL, "is_template_followed" varchar(15) NOT NULL, "is_writeup_correct" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model Evaluation4Supervisor
--
CREATE TABLE "app_evaluation4supervisor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "module_completion" varchar(15) NOT NULL, "student_participation_seminar" varchar(15) NOT NULL, "is_template_followed" varchar(15) NOT NULL, "is_writeup_correct" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model Group
--
CREATE TABLE "app_group" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(20) NOT NULL);
--
-- Create model Project
--
CREATE TABLE "app_project" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "project_name" varchar(100) NOT NULL, "project_description" text NOT NULL, "language" varchar(100) NOT NULL, "functionalities" text NOT NULL, "panel_id" bigint NULL);
--
-- Create model ProjectCategories
--
CREATE TABLE "app_projectcategories" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "category_name" varchar(100) NOT NULL);
--
-- Create model ScopeDocumentEvaluationCriteria
--
CREATE TABLE "app_scopedocumentevaluationcriteria" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "problem_statement" varchar(100) NOT NULL, "validity_of_he_proposed_solution" varchar(100) NOT NULL, "motivation_behind_tools_and_technologies" varchar(100) NOT NULL, "modules" varchar(100) NOT NULL, "task_management" varchar(100) NOT NULL, "related_system_analysis" varchar(100) NOT NULL, "document_format" varchar(100) NOT NULL, "plagiarism_report" boolean NULL, "comments" text NULL, "evaluation_status" boolean NULL);
--
-- Create model SDDEvaluationCommitteeMember
--
CREATE TABLE "app_sddevaluationcommitteemember" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "data_representation_diagram" varchar(15) NOT NULL, "process_flow" varchar(15) NOT NULL, "sdd_design_models" varchar(15) NOT NULL, "algorithm_defined" varchar(15) NOT NULL, "modules_completion_status" varchar(15) NOT NULL, "sdd_template_followed" varchar(15) NOT NULL, "technical_writeup_correct" varchar(15) NOT NULL, "project_domain_knowledge" varchar(15) NOT NULL, "qa_ability" varchar(15) NOT NULL, "proper_attire" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model SDDEvaluationSupervisor
--
CREATE TABLE "app_sddevaluationsupervisor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "data_representation_diagram" varchar(15) NOT NULL, "process_flow" varchar(15) NOT NULL, "design_models" varchar(15) NOT NULL, "algorithms_defined" varchar(15) NOT NULL, "module_completion_status" varchar(15) NOT NULL, "is_sdd_template_followed" varchar(15) NOT NULL, "is_technical_writeup_correct" varchar(15) NOT NULL, "regularity" varchar(15) NOT NULL, "seminar_participation" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model SRSEvaluationCommitteeMember
--
CREATE TABLE "app_srsevaluationcommitteemember" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "analysis_of_existing_systems" varchar(15) NOT NULL, "problem_defined" varchar(15) NOT NULL, "proposed_solution" varchar(15) NOT NULL, "tools_technologies" varchar(15) NOT NULL, "frs_mapped" varchar(15) NOT NULL, "nfrs_mapped" varchar(15) NOT NULL, "requirements_analysis" varchar(15) NOT NULL, "mocks_defined" varchar(15) NOT NULL, "srs_template_followed" varchar(15) NOT NULL, "technical_writeup_correct" varchar(15) NOT NULL, "domain_knowledge" varchar(15) NOT NULL, "qa_ability" varchar(15) NOT NULL, "presentation_attire" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model SRSEvaluationSupervisor
--
CREATE TABLE "app_srsevaluationsupervisor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "regularity" varchar(15) NOT NULL, "srs_are_frs_mapped_to_the_problem" varchar(15) NOT NULL, "srs_are_nfr_mapped_to_the_problem" varchar(15) NOT NULL, "is_srs_storyboarding" varchar(15) NOT NULL, "according_to_requirement" varchar(15) NOT NULL, "is_srs_template_followed" varchar(15) NOT NULL, "is_write_up_correct" varchar(15) NOT NULL, "student_participation" varchar(15) NOT NULL, "comment" varchar(255) NULL);
--
-- Create model Student
--
CREATE TABLE "app_student" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "registration_no" varchar(20) NOT NULL UNIQUE, "department" varchar(100) NULL, "semester" varchar(100) NULL, "batch_no" varchar(100) NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Supervisor
--
CREATE TABLE "app_supervisor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "supervisor_id" varchar(100) NOT NULL UNIQUE, "research_interest" varchar(255) NULL, "academic_background" varchar(255) NULL, "user_id" bigint NOT NULL UNIQUE);
CREATE TABLE "app_supervisor_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "supervisor_id" bigint NOT NULL, "projectcategories_id" bigint NOT NULL);
--
-- Create model SupervisorStudentComments
--
CREATE TABLE "app_supervisorstudentcomments" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "comment" text NOT NULL, "commented_by" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "group_id" bigint NOT NULL, "student_id" bigint NULL, "supervisor_id" bigint NULL);
--
-- Create model SupervisorOfStudentGroup
--
CREATE TABLE "app_supervisorofstudentgroup" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "Scope_document_evaluation_form_id" bigint NULL UNIQUE, "created_by_id" bigint NOT NULL, "evaluation3_committee_member_id" bigint NULL UNIQUE, "evaluation3_supervisor_id" bigint NULL UNIQUE, "evaluation4_committee_member_id" bigint NULL UNIQUE, "evaluation4_supervisor_id" bigint NULL UNIQUE, "group_id" bigint NOT NULL, "project_id" bigint NOT NULL, "sdd_evaluation_committee_member_id" bigint NULL UNIQUE, "sdd_evaluation_supervisor_id" bigint NULL UNIQUE, "srs_evaluation_committee_member_id" bigint NULL UNIQUE, "srs_evaluation_supervisor_id" bigint NULL UNIQUE, "supervisor_id" bigint NOT NULL);
--
-- Add field project_category to project
--
ALTER TABLE "app_project" ADD COLUMN "project_category_id" bigint NOT NULL CONSTRAINT "app_project_project_category_id_376b84ef_fk_app_proje" REFERENCES "app_projectcategories"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_project_project_category_id_376b84ef_fk_app_proje" IMMEDIATE;
--
-- Add field user to project
--
ALTER TABLE "app_project" ADD COLUMN "user_id" bigint NULL CONSTRAINT "app_project_user_id_d99fd018_fk_app_customuser_id" REFERENCES "app_customuser"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_project_user_id_d99fd018_fk_app_customuser_id" IMMEDIATE;
--
-- Create model PasswordResetCode
--
CREATE TABLE "app_passwordresetcode" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(6) NOT NULL, "created_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NOT NULL, "is_used" boolean NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model NotificationPreference
--
CREATE TABLE "app_notificationpreference" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_request_notifications" boolean NOT NULL, "supervisor_request_notifications" boolean NOT NULL, "chat_message_notifications" boolean NOT NULL, "document_notifications" boolean NOT NULL, "evaluation_notifications" boolean NOT NULL, "comment_notifications" boolean NOT NULL, "email_notifications_enabled" boolean NOT NULL, "email_group_requests" boolean NOT NULL, "email_supervisor_requests" boolean NOT NULL, "email_document_updates" boolean NOT NULL, "email_evaluation_updates" boolean NOT NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Notification
--
CREATE TABLE "app_notification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "notification_type" varchar(50) NOT NULL, "title" varchar(255) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "action_url" varchar(255) NULL, "related_document_id" bigint NULL, "related_group_id" bigint NULL, "related_supervisor_group_id" bigint NULL, "user_id" bigint NOT NULL);
--
-- Create model GroupCreationComment
--
CREATE TABLE "app_groupcreationcomment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "comment" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "group_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Add field project_category to group
--
ALTER TABLE "app_group" ADD COLUMN "project_category_id" bigint NOT NULL CONSTRAINT "app_group_project_category_id_124ebef1_fk_app_proje" REFERENCES "app_projectcategories"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_group_project_category_id_124ebef1_fk_app_proje" IMMEDIATE;
--
-- Add field student_1 to group
--
ALTER TABLE "app_group" ADD COLUMN "student_1_id" bigint NOT NULL CONSTRAINT "app_group_student_1_id_97d99bca_fk_app_student_id" REFERENCES "app_student"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_group_student_1_id_97d99bca_fk_app_student_id" IMMEDIATE;
--
-- Add field student_2 to group
--
ALTER TABLE "app_group" ADD COLUMN "student_2_id" bigint NOT NULL CONSTRAINT "app_group_student_2_id_42e4c72d_fk_app_student_id" REFERENCES "app_student"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_group_student_2_id_42e4c72d_fk_app_student_id" IMMEDIATE;
--
-- Add field group to document
--
ALTER TABLE "app_document" ADD COLUMN "group_id" bigint NOT NULL CONSTRAINT "app_document_group_id_9df06c27_fk_app_super" REFERENCES "app_supervisorofstudentgroup"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_document_group_id_9df06c27_fk_app_super" IMMEDIATE;
--
-- Add field uploaded_by to document
--
ALTER TABLE "app_document" ADD COLUMN "uploaded_by_id" bigint NOT NULL CONSTRAINT "app_document_uploaded_by_id_3558c909_fk_app_student_id" REFERENCES "app_student"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_document_uploaded_by_id_3558c909_fk_app_student_id" IMMEDIATE;
--
-- Create model CommitteeMemberTemplates
--
CREATE TABLE "app_committeemembertemplates" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "semester" varchar(100) NOT NULL, "template_type" varchar(50) NOT NULL, "title" varchar(100) NOT NULL, "uploaded_file" varchar(100) NOT NULL, "uploaded_at" timestamp with time zone NOT NULL, "uploaded_by_id" bigint NULL);
--
-- Add field panel to committeemember
--
ALTER TABLE "app_committeemember" ADD COLUMN "panel_id" bigint NOT NULL CONSTRAINT "app_committeemember_panel_id_38e7fabd_fk_app_commi" REFERENCES "app_committeememberpanel"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_committeemember_panel_id_38e7fabd_fk_app_commi" IMMEDIATE;
--
-- Add field user to committeemember
--
ALTER TABLE "app_committeemember" ADD COLUMN "user_id" bigint NOT NULL UNIQUE CONSTRAINT "app_committeemember_user_id_9892048e_fk_app_customuser_id" REFERENCES "app_customuser"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_committeemember_user_id_9892048e_fk_app_customuser_id" IMMEDIATE;
--
-- Create model ChatRoom
--
CREATE TABLE "app_chatroom" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "message" text NOT NULL, "sent_by" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "group_id" bigint NOT NULL, "student_id" bigint NULL, "supervisor_id" bigint NULL);
--
-- Create model AuditLog
--
CREATE TABLE "app_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_type" varchar(50) NOT NULL, "evaluation_type" varchar(50) NULL, "description" text NOT NULL, "field_name" varchar(100) NULL, "old_value" text NULL, "new_value" text NULL, "created_at" timestamp with time zone NOT NULL, "ip_address" inet NULL, "supervisor_group_id" bigint NULL, "user_id" bigint NULL);
--
-- Alter unique_together for group (1 constraint(s))
--
ALTER TABLE "app_group" ADD CONSTRAINT "app_group_student_1_id_student_2_id_id_faa0a798_uniq" UNIQUE ("student_1_id", "student_2_id", "id");
CREATE INDEX "app_customuser_username_e2e5005f_like" ON "app_customuser" ("username" varchar_pattern_ops);
ALTER TABLE "app_customuser_groups" ADD CONSTRAINT "app_customuser_groups_customuser_id_group_id_a5a0ca22_uniq" UNIQUE ("customuser_id", "group_id");
ALTER TABLE "app_customuser_groups" ADD CONSTRAINT "app_customuser_group_customuser_id_164d073f_fk_app_custo" FOREIGN KEY ("customuser_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_customuser_groups" ADD CONSTRAINT "app_customuser_groups_group_id_47e49ebd_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_customuser_groups_customuser_id_164d073f" ON "app_customuser_groups" ("customuser_id");
CREATE INDEX "app_customuser_groups_group_id_47e49ebd" ON "app_customuser_groups" ("group_id");
ALTER TABLE "app_customuser_user_permissions" ADD CONSTRAINT "app_customuser_user_perm_customuser_id_permission_22e31019_uniq" UNIQUE ("customuser_id", "permission_id");
ALTER TABLE "app_customuser_user_permissions" ADD CONSTRAINT "app_customuser_user__customuser_id_4bcbaafb_fk_app_custo" FOREIGN KEY ("customuser_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_customuser_user_permissions" ADD CONSTRAINT "app_customuser_user__permission_id_c5920c75_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_customuser_user_permissions_customuser_id_4bcbaafb" ON "app_customuser_user_permissions" ("customuser_id");
CREATE INDEX "app_customuser_user_permissions_permission_id_c5920c75" ON "app_customuser_user_permissions" ("permission_id");
CREATE INDEX "app_committeemember_committee_id_e8dd585e_like" ON "app_committeemember" ("committee_id" varchar_pattern_ops);
ALTER TABLE "app_project" ADD CONSTRAINT "app_project_panel_id_8b6be3da_fk_app_committeememberpanel_id" FOREIGN KEY ("panel_id") REFERENCES "app_committeememberpanel" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_project_panel_id_8b6be3da" ON "app_project" ("panel_id");
ALTER TABLE "app_student" ADD CONSTRAINT "app_student_user_id_49aed64b_fk_app_customuser_id" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_student_registration_no_503b33fe_like" ON "app_student" ("registration_no" varchar_pattern_ops);
ALTER TABLE "app_supervisor" ADD CONSTRAINT "app_supervisor_user_id_73c5cbf3_fk_app_customuser_id" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_supervisor_supervisor_id_e86d50a9_like" ON "app_supervisor" ("supervisor_id" varchar_pattern_ops);
ALTER TABLE "app_supervisor_category" ADD CONSTRAINT "app_supervisor_category_supervisor_id_projectcat_ed78dd24_uniq" UNIQUE ("supervisor_id", "projectcategories_id");
ALTER TABLE "app_supervisor_category" ADD CONSTRAINT "app_supervisor_categ_supervisor_id_3f52f072_fk_app_super" FOREIGN KEY ("supervisor_id") REFERENCES "app_supervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisor_category" ADD CONSTRAINT "app_supervisor_categ_projectcategories_id_ea0fbe0e_fk_app_proje" FOREIGN KEY ("projectcategories_id") REFERENCES "app_projectcategories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_supervisor_category_supervisor_id_3f52f072" ON "app_supervisor_category" ("supervisor_id");
CREATE INDEX "app_supervisor_category_projectcategories_id_ea0fbe0e" ON "app_supervisor_category" ("projectcategories_id");
ALTER TABLE "app_supervisorstudentcomments" ADD CONSTRAINT "app_supervisorstudentcomments_group_id_5652e7e1_fk_app_group_id" FOREIGN KEY ("group_id") REFERENCES "app_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorstudentcomments" ADD CONSTRAINT "app_supervisorstuden_student_id_4797ab2b_fk_app_stude" FOREIGN KEY ("student_id") REFERENCES "app_student" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorstudentcomments" ADD CONSTRAINT "app_supervisorstuden_supervisor_id_eff1791b_fk_app_super" FOREIGN KEY ("supervisor_id") REFERENCES "app_supervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_supervisorstudentcomments_group_id_5652e7e1" ON "app_supervisorstudentcomments" ("group_id");
CREATE INDEX "app_supervisorstudentcomments_student_id_4797ab2b" ON "app_supervisorstudentcomments" ("student_id");
CREATE INDEX "app_supervisorstudentcomments_supervisor_id_eff1791b" ON "app_supervisorstudentcomments" ("supervisor_id");
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstudentg_group_id_supervisor_id_1eb9b20e_uniq" UNIQUE ("group_id", "supervisor_id");
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_Scope_document_evalu_d886f777_fk_app_scope" FOREIGN KEY ("Scope_document_evaluation_form_id") REFERENCES "app_scopedocumentevaluationcriteria" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_created_by_id_33263203_fk_app_stude" FOREIGN KEY ("created_by_id") REFERENCES "app_student" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_evaluation3_committe_f5f29a23_fk_app_evalu" FOREIGN KEY ("evaluation3_committee_member_id") REFERENCES "app_evaluation3committeemember" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_evaluation3_supervis_90024ed0_fk_app_evalu" FOREIGN KEY ("evaluation3_supervisor_id") REFERENCES "app_evaluation3supervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_evaluation4_committe_20564d5c_fk_app_evalu" FOREIGN KEY ("evaluation4_committee_member_id") REFERENCES "app_evaluation4committeemember" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_evaluation4_supervis_5b2da05f_fk_app_evalu" FOREIGN KEY ("evaluation4_supervisor_id") REFERENCES "app_evaluation4supervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstudentgroup_group_id_206fd23c_fk_app_group_id" FOREIGN KEY ("group_id") REFERENCES "app_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_project_id_a9f33382_fk_app_proje" FOREIGN KEY ("project_id") REFERENCES "app_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_sdd_evaluation_commi_8abb2b7d_fk_app_sddev" FOREIGN KEY ("sdd_evaluation_committee_member_id") REFERENCES "app_sddevaluationcommitteemember" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_sdd_evaluation_super_750f5ccd_fk_app_sddev" FOREIGN KEY ("sdd_evaluation_supervisor_id") REFERENCES "app_sddevaluationsupervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_srs_evaluation_commi_eb929bbf_fk_app_srsev" FOREIGN KEY ("srs_evaluation_committee_member_id") REFERENCES "app_srsevaluationcommitteemember" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_srs_evaluation_super_df308612_fk_app_srsev" FOREIGN KEY ("srs_evaluation_supervisor_id") REFERENCES "app_srsevaluationsupervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_supervisorofstudentgroup" ADD CONSTRAINT "app_supervisorofstud_supervisor_id_e24580e7_fk_app_super" FOREIGN KEY ("supervisor_id") REFERENCES "app_supervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_supervisorofstudentgroup_created_by_id_33263203" ON "app_supervisorofstudentgroup" ("created_by_id");
CREATE INDEX "app_supervisorofstudentgroup_group_id_206fd23c" ON "app_supervisorofstudentgroup" ("group_id");
CREATE INDEX "app_supervisorofstudentgroup_project_id_a9f33382" ON "app_supervisorofstudentgroup" ("project_id");
CREATE INDEX "app_supervisorofstudentgroup_supervisor_id_e24580e7" ON "app_supervisorofstudentgroup" ("supervisor_id");
CREATE INDEX "app_project_project_category_id_376b84ef" ON "app_project" ("project_category_id");
CREATE INDEX "app_project_user_id_d99fd018" ON "app_project" ("user_id");
ALTER TABLE "app_passwordresetcode" ADD CONSTRAINT "app_passwordresetcode_user_id_bab2d9db_fk_app_customuser_id" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_passwordresetcode_user_id_bab2d9db" ON "app_passwordresetcode" ("user_id");
ALTER TABLE "app_notificationpreference" ADD CONSTRAINT "app_notificationpref_user_id_2a69cc3a_fk_app_custo" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_notification" ADD CONSTRAINT "app_notification_related_document_id_41669787_fk_app_docum" FOREIGN KEY ("related_document_id") REFERENCES "app_document" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_notification" ADD CONSTRAINT "app_notification_related_group_id_e92b3edb_fk_app_group_id" FOREIGN KEY ("related_group_id") REFERENCES "app_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_notification" ADD CONSTRAINT "app_notification_related_supervisor_g_80ea8a0b_fk_app_super" FOREIGN KEY ("related_supervisor_group_id") REFERENCES "app_supervisorofstudentgroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_notification" ADD CONSTRAINT "app_notification_user_id_6ab9311d_fk_app_customuser_id" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_notification_related_document_id_41669787" ON "app_notification" ("related_document_id");
CREATE INDEX "app_notification_related_group_id_e92b3edb" ON "app_notification" ("related_group_id");
CREATE INDEX "app_notification_related_supervisor_group_id_80ea8a0b" ON "app_notification" ("related_supervisor_group_id");
CREATE INDEX "app_notification_user_id_6ab9311d" ON "app_notification" ("user_id");
ALTER TABLE "app_groupcreationcomment" ADD CONSTRAINT "app_groupcreationcomment_group_id_04583372_fk_app_group_id" FOREIGN KEY ("group_id") REFERENCES "app_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_groupcreationcomment" ADD CONSTRAINT "app_groupcreationcomment_student_id_85b210b7_fk_app_student_id" FOREIGN KEY ("student_id") REFERENCES "app_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_groupcreationcomment_group_id_04583372" ON "app_groupcreationcomment" ("group_id");
CREATE INDEX "app_groupcreationcomment_student_id_85b210b7" ON "app_groupcreationcomment" ("student_id");
CREATE INDEX "app_group_project_category_id_124ebef1" ON "app_group" ("project_category_id");
CREATE INDEX "app_group_student_1_id_97d99bca" ON "app_group" ("student_1_id");
CREATE INDEX "app_group_student_2_id_42e4c72d" ON "app_group" ("student_2_id");
CREATE INDEX "app_document_group_id_9df06c27" ON "app_document" ("group_id");
CREATE INDEX "app_document_uploaded_by_id_3558c909" ON "app_document" ("uploaded_by_id");
ALTER TABLE "app_committeemembertemplates" ADD CONSTRAINT "app_committeemembert_uploaded_by_id_e75c7f8a_fk_app_commi" FOREIGN KEY ("uploaded_by_id") REFERENCES "app_committeemember" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_committeemembertemplates_uploaded_by_id_e75c7f8a" ON "app_committeemembertemplates" ("uploaded_by_id");
CREATE INDEX "app_committeemember_panel_id_38e7fabd" ON "app_committeemember" ("panel_id");
ALTER TABLE "app_chatroom" ADD CONSTRAINT "app_chatroom_group_id_dbaa1dd8_fk_app_super" FOREIGN KEY ("group_id") REFERENCES "app_supervisorofstudentgroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_chatroom" ADD CONSTRAINT "app_chatroom_student_id_2987ba7b_fk_app_student_id" FOREIGN KEY ("student_id") REFERENCES "app_student" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_chatroom" ADD CONSTRAINT "app_chatroom_supervisor_id_6050c84a_fk_app_supervisor_id" FOREIGN KEY ("supervisor_id") REFERENCES "app_supervisor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_chatroom_group_id_dbaa1dd8" ON "app_chatroom" ("group_id");
CREATE INDEX "app_chatroom_student_id_2987ba7b" ON "app_chatroom" ("student_id");
CREATE INDEX "app_chatroom_supervisor_id_6050c84a" ON "app_chatroom" ("supervisor_id");
ALTER TABLE "app_auditlog" ADD CONSTRAINT "app_auditlog_supervisor_group_id_f00145cc_fk_app_super" FOREIGN KEY ("supervisor_group_id") REFERENCES "app_supervisorofstudentgroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_auditlog" ADD CONSTRAINT "app_auditlog_user_id_58b3ddfe_fk_app_customuser_id" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_auditlog_supervisor_group_id_f00145cc" ON "app_auditlog" ("supervisor_group_id");
CREATE INDEX "app_auditlog_user_id_58b3ddfe" ON "app_auditlog" ("user_id");
COMMIT;


-- Migration: app - 0002_add_external_examiner_models
BEGIN;
--
-- Create model ExternalExaminer
--
CREATE TABLE "app_externalexaminer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "external_id" varchar(50) NOT NULL UNIQUE, "institution" varchar(200) NOT NULL, "designation" varchar(50) NOT NULL, "specialization" varchar(200) NULL, "contact_number" varchar(20) NULL, "address" text NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model ExternalGroup
--
CREATE TABLE "app_externalgroup" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "semester" varchar(50) NOT NULL, "status" varchar(20) NOT NULL, "max_groups" integer NOT NULL CHECK ("max_groups" >= 0), "evaluation_date" date NULL, "evaluation_venue" varchar(200) NULL, "notes" text NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Add field external_evaluation_status to supervisorofstudentgroup
--
ALTER TABLE "app_supervisorofstudentgroup" ADD COLUMN "external_evaluation_status" varchar(20) DEFAULT 'not_applicable' NOT NULL;
ALTER TABLE "app_supervisorofstudentgroup" ALTER COLUMN "external_evaluation_status" DROP DEFAULT;
--
-- Add field is_ready_for_external to supervisorofstudentgroup
--
ALTER TABLE "app_supervisorofstudentgroup" ADD COLUMN "is_ready_for_external" boolean DEFAULT false NOT NULL;
ALTER TABLE "app_supervisorofstudentgroup" ALTER COLUMN "is_ready_for_external" DROP DEFAULT;
--
-- Alter field user_type on customuser
--
-- (no-op)
--
-- Create model ExternalGroupAssignment
--
CREATE TABLE "app_externalgroupassignment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "slot_number" integer NULL CHECK ("slot_number" >= 0), "slot_time" time NULL, "status" varchar(20) NOT NULL, "assigned_at" timestamp with time zone NOT NULL, "assigned_by_id" bigint NULL, "external_group_id" bigint NOT NULL, "supervisor_group_id" bigint NOT NULL UNIQUE);
--
-- Add field created_by to externalgroup
--
ALTER TABLE "app_externalgroup" ADD COLUMN "created_by_id" bigint NULL CONSTRAINT "app_externalgroup_created_by_id_1ed79856_fk_app_customuser_id" REFERENCES "app_customuser"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_externalgroup_created_by_id_1ed79856_fk_app_customuser_id" IMMEDIATE;
--
-- Add field external_examiner to externalgroup
--
ALTER TABLE "app_externalgroup" ADD COLUMN "external_examiner_id" bigint NOT NULL CONSTRAINT "app_externalgroup_external_examiner_id_1d2bee77_fk_app_exter" REFERENCES "app_externalexaminer"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_externalgroup_external_examiner_id_1d2bee77_fk_app_exter" IMMEDIATE;
--
-- Add field user to externalexaminer
--
ALTER TABLE "app_externalexaminer" ADD COLUMN "user_id" bigint NOT NULL UNIQUE CONSTRAINT "app_externalexaminer_user_id_63fb58fe_fk_app_customuser_id" REFERENCES "app_customuser"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_externalexaminer_user_id_63fb58fe_fk_app_customuser_id" IMMEDIATE;
--
-- Create model ExternalEvaluation
--
CREATE TABLE "app_externalevaluation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "project_completion" varchar(15) NOT NULL, "code_quality" varchar(15) NOT NULL, "functionality" varchar(15) NOT NULL, "understanding_of_technology" varchar(15) NOT NULL, "problem_solving" varchar(15) NOT NULL, "innovation" varchar(15) NOT NULL, "presentation_clarity" varchar(15) NOT NULL, "communication" varchar(15) NOT NULL, "time_management" varchar(15) NOT NULL, "documentation_completeness" varchar(15) NOT NULL, "documentation_quality" varchar(15) NOT NULL, "qa_response" varchar(15) NOT NULL, "overall_comment" text NULL, "strengths" text NULL, "areas_of_improvement" text NULL, "is_pass" boolean NOT NULL, "evaluated_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "assignment_id" bigint NOT NULL UNIQUE);
--
-- Create model EvaluationSchedule
--
CREATE TABLE "app_evaluationschedule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "evaluation_type" varchar(50) NOT NULL, "semester" varchar(50) NOT NULL, "date" date NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "venue" varchar(200) NOT NULL, "status" varchar(20) NOT NULL, "notes" text NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "external_group_id" bigint NULL, "panel_id" bigint NULL);
CREATE INDEX "app_externalexaminer_external_id_5ed102b4_like" ON "app_externalexaminer" ("external_id" varchar_pattern_ops);
ALTER TABLE "app_externalgroupassignment" ADD CONSTRAINT "app_externalgroupassignm_external_group_id_superv_ea37ac78_uniq" UNIQUE ("external_group_id", "supervisor_group_id");
ALTER TABLE "app_externalgroupassignment" ADD CONSTRAINT "app_externalgroupass_assigned_by_id_a4127e85_fk_app_custo" FOREIGN KEY ("assigned_by_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_externalgroupassignment" ADD CONSTRAINT "app_externalgroupass_external_group_id_e90eb7b8_fk_app_exter" FOREIGN KEY ("external_group_id") REFERENCES "app_externalgroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_externalgroupassignment" ADD CONSTRAINT "app_externalgroupass_supervisor_group_id_3984b25f_fk_app_super" FOREIGN KEY ("supervisor_group_id") REFERENCES "app_supervisorofstudentgroup" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_externalgroupassignment_assigned_by_id_a4127e85" ON "app_externalgroupassignment" ("assigned_by_id");
CREATE INDEX "app_externalgroupassignment_external_group_id_e90eb7b8" ON "app_externalgroupassignment" ("external_group_id");
CREATE INDEX "app_externalgroup_created_by_id_1ed79856" ON "app_externalgroup" ("created_by_id");
CREATE INDEX "app_externalgroup_external_examiner_id_1d2bee77" ON "app_externalgroup" ("external_examiner_id");
ALTER TABLE "app_externalevaluation" ADD CONSTRAINT "app_externalevaluati_assignment_id_ff68160a_fk_app_exter" FOREIGN KEY ("assignment_id") REFERENCES "app_externalgroupassignment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_evaluationschedule" ADD CONSTRAINT "app_evaluationschedu_created_by_id_356f47dd_fk_app_custo" FOREIGN KEY ("created_by_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_evaluationschedule" ADD CONSTRAINT "app_evaluationschedu_external_group_id_37fd8488_fk_app_exter" FOREIGN KEY ("external_group_id") REFERENCES "app_externalgroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_evaluationschedule" ADD CONSTRAINT "app_evaluationschedu_panel_id_698a2409_fk_app_commi" FOREIGN KEY ("panel_id") REFERENCES "app_committeememberpanel" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_evaluationschedule_created_by_id_356f47dd" ON "app_evaluationschedule" ("created_by_id");
CREATE INDEX "app_evaluationschedule_external_group_id_37fd8488" ON "app_evaluationschedule" ("external_group_id");
CREATE INDEX "app_evaluationschedule_panel_id_698a2409" ON "app_evaluationschedule" ("panel_id");
COMMIT;


-- Migration: app - 0003_add_document_requirements
BEGIN;
--
-- Create model DocumentRequirement
--
CREATE TABLE "app_documentrequirement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "document_type" varchar(50) NOT NULL, "title" varchar(200) NOT NULL, "deadline" timestamp with time zone NOT NULL, "semester" varchar(20) NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
ALTER TABLE "app_documentrequirement" ADD CONSTRAINT "app_documentrequirem_created_by_id_be3def64_fk_app_commi" FOREIGN KEY ("created_by_id") REFERENCES "app_committeemember" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_documentrequirement_created_by_id_be3def64" ON "app_documentrequirement" ("created_by_id");
COMMIT;


-- Migration: app - 0004_add_submitted_to_committee
BEGIN;
--
-- Add field submitted_to_committee to document
--
ALTER TABLE "app_document" ADD COLUMN "submitted_to_committee" boolean DEFAULT false NOT NULL;
ALTER TABLE "app_document" ALTER COLUMN "submitted_to_committee" DROP DEFAULT;
--
-- Add field submitted_to_committee_at to document
--
ALTER TABLE "app_document" ADD COLUMN "submitted_to_committee_at" timestamp with time zone NULL;
COMMIT;


-- Migration: app - 0005_alter_group_student_2
BEGIN;
--
-- Alter field student_2 on group
--
SET CONSTRAINTS "app_group_student_2_id_42e4c72d_fk_app_student_id" IMMEDIATE; ALTER TABLE "app_group" DROP CONSTRAINT "app_group_student_2_id_42e4c72d_fk_app_student_id";
ALTER TABLE "app_group" ALTER COLUMN "student_2_id" DROP NOT NULL;
ALTER TABLE "app_group" ADD CONSTRAINT "app_group_student_2_id_42e4c72d_fk_app_student_id" FOREIGN KEY ("student_2_id") REFERENCES "app_student" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;


-- Migration: token_blacklist - 0001_initial
BEGIN;
--
-- Create model BlacklistedToken
--
CREATE TABLE "token_blacklist_blacklistedtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "blacklisted_at" timestamp with time zone NOT NULL);
--
-- Create model OutstandingToken
--
CREATE TABLE "token_blacklist_outstandingtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "jti" uuid NOT NULL UNIQUE, "token" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL);
--
-- Add field token to blacklistedtoken
--
ALTER TABLE "token_blacklist_blacklistedtoken" ADD COLUMN "token_id" integer NOT NULL UNIQUE CONSTRAINT "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" REFERENCES "token_blacklist_outstandingtoken"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" IMMEDIATE;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_app_custo" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");
COMMIT;


-- Migration: token_blacklist - 0002_outstandingtoken_jti_hex
BEGIN;
--
-- Add field jti_hex to outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ADD COLUMN "jti_hex" varchar(255) NULL;
COMMIT;


-- Migration: token_blacklist - 0003_auto_20171017_2007
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;


-- Migration: token_blacklist - 0004_auto_20171017_2013
BEGIN;
--
-- Alter field jti_hex on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "jti_hex" SET NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti_hex");
CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "token_blacklist_outstandingtoken" ("jti_hex" varchar_pattern_ops);
COMMIT;


-- Migration: token_blacklist - 0005_remove_outstandingtoken_jti
BEGIN;
--
-- Remove field jti from outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" DROP COLUMN "jti" CASCADE;
COMMIT;


-- Migration: token_blacklist - 0006_auto_20171017_2113
BEGIN;
--
-- Rename field jti_hex on outstandingtoken to jti
--
ALTER TABLE "token_blacklist_outstandingtoken" RENAME COLUMN "jti_hex" TO "jti";
COMMIT;


-- Migration: token_blacklist - 0007_auto_20171017_2214
BEGIN;
--
-- Alter field created_at on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "created_at" DROP NOT NULL;
--
-- Alter field user on outstandingtoken
--
SET CONSTRAINTS "token_blacklist_outs_user_id_83bc629a_fk_app_custo" IMMEDIATE; ALTER TABLE "token_blacklist_outstandingtoken" DROP CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_app_custo";
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_app_custo" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;


-- Migration: token_blacklist - 0008_migrate_to_bigautofield
BEGIN;
--
-- Alter field id on blacklistedtoken
--
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "token_blacklist_blacklistedtoken_id_seq" AS bigint;
--
-- Alter field id on outstandingtoken
--
SET CONSTRAINTS "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" IMMEDIATE; ALTER TABLE "token_blacklist_blacklistedtoken" DROP CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk";
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "token_blacklist_outstandingtoken_id_seq" AS bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "token_id" TYPE bigint USING "token_id"::bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;


-- Migration: token_blacklist - 0010_fix_migrate_to_bigautofield
BEGIN;
--
-- Alter field id on blacklistedtoken
--
-- (no-op)
--
-- Alter field id on outstandingtoken
--
-- (no-op)
COMMIT;


-- Migration: token_blacklist - 0012_alter_outstandingtoken_user
BEGIN;
--
-- Alter field user on outstandingtoken
--
-- (no-op)
COMMIT;


-- Migration: admin - 0001_initial
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_app_customuser_id" FOREIGN KEY ("user_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;


-- Migration: admin - 0002_logentry_remove_auto_add
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;


-- Migration: admin - 0003_logentry_add_action_flag_choices
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;


-- Migration: sessions - 0001_initial
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;


