# Generated by Django 4.2.27 on 2026-01-24 11:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('committee_member', 'Committee Member')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMemberPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('scope_document', 'Scope Document'), ('srs_document', 'SRS Document'), ('sdd_document', 'SDD Document'), ('final_report_document', 'Final Report Document'), ('presentation_document', 'Presentation Document')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted_by_student', 'Accepted by Student'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation3CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_completion', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('software_testing', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('qa_ability', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('proper_attire', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation3Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_completion', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('software_testing', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('regularity', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('project_domain_knowledge', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation4CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_completion', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('software_testing', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('qa_ability', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('proper_attire', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation4Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_completion', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('student_participation_seminar', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('functionalities', models.TextField()),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.committeememberpanel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeDocumentEvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('validity_of_he_proposed_solution', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('motivation_behind_tools_and_technologies', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('modules', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('task_management', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('related_system_analysis', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('document_format', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=100)),
                ('plagiarism_report', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evaluation_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDDEvaluationCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_representation_diagram', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('process_flow', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('sdd_design_models', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('algorithm_defined', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('modules_completion_status', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('sdd_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('technical_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('project_domain_knowledge', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('qa_ability', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('proper_attire', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDDEvaluationSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_representation_diagram', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('process_flow', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('design_models', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('algorithms_defined', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('module_completion_status', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_sdd_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_technical_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('regularity', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('seminar_participation', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRSEvaluationCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_of_existing_systems', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('problem_defined', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('proposed_solution', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('tools_technologies', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('frs_mapped', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('nfrs_mapped', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('requirements_analysis', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('mocks_defined', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('srs_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('technical_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('domain_knowledge', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('qa_ability', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('presentation_attire', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRSEvaluationSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regularity', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('srs_are_frs_mapped_to_the_problem', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('srs_are_nfr_mapped_to_the_problem', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_srs_storyboarding', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('according_to_requirement', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_srs_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_write_up_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('student_participation', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(blank=True, choices=[('semester_6', 'Semester 6'), ('semester_7', 'Semester 7'), ('semester_8', 'Semester 8')], max_length=100, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(max_length=100, unique=True)),
                ('research_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_background', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ManyToManyField(blank=True, related_name='supervisor', to='app.projectcategories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorStudentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_by', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to='app.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_comments', to='app.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_comments', to='app.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorOfStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted_by_student', 'Accepted by Student'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Scope_document_evaluation_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_document_evaluation_form', to='app.scopedocumentevaluationcriteria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_request_created_by', to='app.student')),
                ('evaluation3_committee_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.evaluation3committeemember')),
                ('evaluation3_supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.evaluation3supervisor')),
                ('evaluation4_committee_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.evaluation4committeemember')),
                ('evaluation4_supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.evaluation4supervisor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_request', to='app.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.project')),
                ('sdd_evaluation_committee_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.sddevaluationcommitteemember')),
                ('sdd_evaluation_supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.sddevaluationsupervisor')),
                ('srs_evaluation_committee_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.srsevaluationcommitteemember')),
                ('srs_evaluation_supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.srsevaluationsupervisor')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_request', to='app.supervisor')),
            ],
            options={
                'unique_together': {('group', 'supervisor')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='app.projectcategories'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_request_notifications', models.BooleanField(default=True)),
                ('supervisor_request_notifications', models.BooleanField(default=True)),
                ('chat_message_notifications', models.BooleanField(default=True)),
                ('document_notifications', models.BooleanField(default=True)),
                ('evaluation_notifications', models.BooleanField(default=True)),
                ('comment_notifications', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('email_group_requests', models.BooleanField(default=False)),
                ('email_supervisor_requests', models.BooleanField(default=False)),
                ('email_document_updates', models.BooleanField(default=False)),
                ('email_evaluation_updates', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('group_request', 'Group Request'), ('group_request_accepted', 'Group Request Accepted'), ('group_request_rejected', 'Group Request Rejected'), ('supervisor_request', 'Supervisor Request'), ('supervisor_request_accepted', 'Supervisor Request Accepted'), ('supervisor_request_rejected', 'Supervisor Request Rejected'), ('new_chat_message', 'New Chat Message'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('evaluation_completed', 'Evaluation Completed'), ('new_comment', 'New Comment'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.document')),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.group')),
                ('related_supervisor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.supervisorofstudentgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupCreationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmate_project', to='app.projectcategories'),
        ),
        migrations.AddField(
            model_name='group',
            name='student_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_request', to='app.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='student_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_request', to='app.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.supervisorofstudentgroup'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='app.student'),
        ),
        migrations.CreateModel(
            name='CommitteeMemberTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('semester_6', 'Semester 6'), ('semester_7', 'Semester 7'), ('semester_8', 'Semester 8')], max_length=100)),
                ('template_type', models.CharField(choices=[('scope_documents_template', 'Scope Document Template'), ('srs_template', 'SRS Template'), ('sdd_template', 'SDD Template'), ('final_report_template', 'Final Report Template')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='doc_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_templates', to='app.committeemember')),
            ],
        ),
        migrations.AddField(
            model_name='committeemember',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_member', to='app.committeememberpanel'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_by', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.supervisorofstudentgroup')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_messages', to='app.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_messages', to='app.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('evaluation_update', 'Evaluation Update'), ('document_status_change', 'Document Status Change'), ('group_status_change', 'Group Status Change'), ('supervisor_request_update', 'Supervisor Request Update')], default='evaluation_update', max_length=50)),
                ('evaluation_type', models.CharField(blank=True, choices=[('scope_document', 'Scope Document'), ('srs_supervisor', 'SRS Supervisor'), ('srs_committee', 'SRS Committee Member'), ('sdd_supervisor', 'SDD Supervisor'), ('sdd_committee', 'SDD Committee Member'), ('evaluation3_supervisor', 'Evaluation 3 Supervisor'), ('evaluation3_committee', 'Evaluation 3 Committee Member'), ('evaluation4_supervisor', 'Evaluation 4 Supervisor'), ('evaluation4_committee', 'Evaluation 4 Committee Member')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('supervisor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.supervisorofstudentgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('student_1', 'student_2', 'id')},
        ),
    ]
