# Generated by Django 4.2.27 on 2026-01-24 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalExaminer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('institution', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('industry_expert', 'Industry Expert'), ('visiting_faculty', 'Visiting Faculty')], default='professor', max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Examiner',
                'verbose_name_plural': 'External Examiners',
            },
        ),
        migrations.CreateModel(
            name='ExternalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('max_groups', models.PositiveIntegerField(default=7)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('evaluation_venue', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Group',
                'verbose_name_plural': 'External Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supervisorofstudentgroup',
            name='external_evaluation_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned to External'), ('evaluated', 'Evaluated')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisorofstudentgroup',
            name='is_ready_for_external',
            field=models.BooleanField(default=False, help_text='Set to True when group has completed all internal evaluations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('committee_member', 'Committee Member'), ('external_examiner', 'External Examiner')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExternalGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(blank=True, null=True)),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('evaluated', 'Evaluated'), ('absent', 'Absent')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('external_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.externalgroup')),
                ('supervisor_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_assignment', to='app.supervisorofstudentgroup')),
            ],
            options={
                'verbose_name': 'External Group Assignment',
                'verbose_name_plural': 'External Group Assignments',
                'ordering': ['slot_number', 'assigned_at'],
                'unique_together': {('external_group', 'supervisor_group')},
            },
        ),
        migrations.AddField(
            model_name='externalgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalgroup',
            name='external_examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_groups', to='app.externalexaminer'),
        ),
        migrations.AddField(
            model_name='externalexaminer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_examiner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExternalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_completion', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Is the project fully implemented? (10 marks)', max_length=15)),
                ('code_quality', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Quality of code, architecture, best practices (10 marks)', max_length=15)),
                ('functionality', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Does the project work as expected? (10 marks)', max_length=15)),
                ('understanding_of_technology', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Understanding of technologies used (10 marks)', max_length=15)),
                ('problem_solving', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Ability to solve technical problems (10 marks)', max_length=15)),
                ('innovation', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Innovation and creativity in solution (5 marks)', max_length=15)),
                ('presentation_clarity', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Clarity of presentation (10 marks)', max_length=15)),
                ('communication', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Communication skills (5 marks)', max_length=15)),
                ('time_management', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Presentation time management (5 marks)', max_length=15)),
                ('documentation_completeness', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Is documentation complete? (8 marks)', max_length=15)),
                ('documentation_quality', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Quality of documentation (7 marks)', max_length=15)),
                ('qa_response', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', help_text='Response to questions (10 marks)', max_length=15)),
                ('overall_comment', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_of_improvement', models.TextField(blank=True, null=True)),
                ('is_pass', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='app.externalgroupassignment')),
            ],
            options={
                'verbose_name': 'External Evaluation',
                'verbose_name_plural': 'External Evaluations',
            },
        ),
        migrations.CreateModel(
            name='EvaluationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('evaluation_type', models.CharField(choices=[('scope', 'Scope Document Evaluation'), ('srs', 'SRS Evaluation'), ('sdd', 'SDD Evaluation'), ('midterm', 'Midterm Evaluation'), ('internal_final', 'Internal Final Evaluation'), ('external_final', 'External Final Evaluation')], max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('external_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.externalgroup')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.committeememberpanel')),
            ],
            options={
                'verbose_name': 'Evaluation Schedule',
                'verbose_name_plural': 'Evaluation Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
