# Generated by Django 4.2.27 on 2026-01-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_external_examiner_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('scope_document', 'Scope Document'), ('srs_document', 'SRS Document'), ('sdd_document', 'SDD Document'), ('final_report_document', 'Final Report Document'), ('presentation_document', 'Presentation Document')], max_length=50)),
                ('title', models.CharField(help_text="Short label, e.g. 'SRS Submission - Phase 1'", max_length=200)),
                ('deadline', models.DateTimeField(help_text='Upload deadline for this document type')),
                ('semester', models.CharField(blank=True, choices=[('semester_6', 'Semester 6'), ('semester_7', 'Semester 7'), ('semester_8', 'Semester 8')], help_text='If set, only students in this semester see this requirement', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requirements', to='app.committeemember')),
            ],
            options={
                'ordering': ['deadline', 'document_type'],
            },
        ),
    ]
