# Generated by Django 4.2.27 on 2026-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_document_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='submitted_to_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='submitted_to_committee_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
