# Generated by Django 4.2.30 on 2026-08-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_submitted_to_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_request', to='app.student'),
        ),
    ]
