# Generated by Django 4.2.30 on 2026-08-27 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_group_student_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_number', models.IntegerField(default=1)),
                ('council_name', models.CharField(max_length=255)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.CharField(choices=[('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều')], default='MORNING', max_length=50)),
                ('defense_room', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_councils', to='app.academicbatch')),
            ],
            options={
                'ordering': ['batch', 'council_number'],
            },
        ),
        migrations.CreateModel(
            name='GraduationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title_vi', models.CharField(max_length=500)),
                ('topic_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Đã phân GVHD'), ('OUTLINE_PENDING', 'Chờ duyệt đề cương'), ('OUTLINE_REVISION', 'Yêu cầu sửa đề cương'), ('OUTLINE_APPROVED', 'Đề cương đã duyệt'), ('IN_PROGRESS', 'Đang thực hiện đồ án'), ('DEFENSE_READY', 'Đủ điều kiện bảo vệ'), ('PASSED', 'Bảo vệ thành công - Đạt'), ('FAILED', 'Không đạt'), ('DEFERRED', 'Bảo lưu đồ án')], default='ALLOCATED', max_length=50)),
                ('supervisor_score', models.FloatField(blank=True, null=True)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('is_eligible_for_defense', models.BooleanField(default=False)),
                ('reviewer_score', models.FloatField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_projects', to='app.academicbatch')),
                ('council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.defensecouncil')),
            ],
            options={
                'ordering': ['student__user__last_name', 'student__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTopicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='academic_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='OutlineReviewGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_review_groups', to='app.academicbatch')),
                ('members', models.ManyToManyField(blank=True, related_name='outline_groups', to='app.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='OutlineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_file', models.FileField(blank=True, null=True, upload_to='outlines/')),
                ('verdict', models.CharField(choices=[('PENDING', 'Chờ xét duyệt'), ('APPROVED', 'Đạt yêu cầu'), ('REVISION_REQUIRED', 'Yêu cầu chỉnh sửa'), ('REJECTED', 'Không đạt / Hủy đề tài')], default='PENDING', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline_review', to='app.graduationproject')),
                ('review_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_outlines', to='app.outlinereviewgroup')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_outline_reviews', to='app.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interning', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tentative_title', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_submissions', to='app.academicbatch')),
                ('preferred_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_students', to='app.supervisor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_info', to='app.student')),
                ('topic_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='app.projecttopicarea')),
            ],
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_graduation_projects', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_project', to='app.student'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_graduation_projects', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='topic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.projecttopicarea'),
        ),
        migrations.CreateModel(
            name='FinalGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_score', models.FloatField(blank=True, null=True)),
                ('reviewer_score', models.FloatField(blank=True, null=True)),
                ('council_avg_score', models.FloatField(blank=True, null=True)),
                ('final_score_10', models.FloatField(blank=True, null=True)),
                ('final_score_4', models.FloatField(blank=True, null=True)),
                ('final_letter_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_summary', to='app.graduationproject')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_supervisor', models.FloatField(default=0.4)),
                ('weight_reviewer', models.FloatField(default=0.2)),
                ('weight_council', models.FloatField(default=0.4)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_policy', to='app.academicbatch')),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('VIET_ANH', 'Công nghệ thông tin Việt - Anh'), ('DAI_TRA', 'Công nghệ thông tin Đại trà'), ('KHMT', 'Khoa học máy tính'), ('KHOA_CU', 'Sinh viên Khóa cũ')], default='DAI_TRA', max_length=50)),
                ('class_group', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='app.academicbatch')),
            ],
            options={
                'ordering': ['class_code'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHAIR', 'Chủ tịch hội đồng'), ('SECRETARY', 'Ủy viên, Thư ký'), ('MEMBER', 'Ủy viên'), ('EXTERNAL_MEMBER', 'Ủy viên ngoài trường')], default='MEMBER', max_length=50)),
                ('external_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.defensecouncil')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_memberships', to='app.supervisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('council', 'user')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='academic_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.academicbatch'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.courseclass'),
        ),
        migrations.CreateModel(
            name='WeeklyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('summary_content', models.TextField()),
                ('planned_tasks', models.TextField(blank=True, null=True)),
                ('git_commit_link', models.URLField(blank=True, max_length=500, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='weekly_reports/')),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('supervisor_rating', models.CharField(choices=[('PENDING', 'Chưa đánh giá'), ('GOOD', 'Tốt / Đạt tiến độ'), ('ACCEPTABLE', 'Chấp nhận được'), ('LATE', 'Chậm tiến độ'), ('UNSATISFACTORY', 'Không đạt yêu cầu')], default='PENDING', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='app.graduationproject')),
            ],
            options={
                'ordering': ['project', 'week_number'],
                'unique_together': {('project', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('viet_anh_quota', models.IntegerField(default=0, help_text='Chỉ tiêu lớp CLC Việt - Anh')),
                ('general_cntt_quota', models.IntegerField(default=0, help_text='Chỉ tiêu lớp Đại trà & KHMT')),
                ('max_total_quota', models.IntegerField(default=0, help_text='Tổng chỉ tiêu tối đa')),
                ('current_assigned', models.IntegerField(default=0, help_text='Số lượng SV đã được phân')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_quotas', to='app.academicbatch')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='app.supervisor')),
            ],
            options={
                'ordering': ['supervisor__user__first_name', 'supervisor__user__last_name'],
                'unique_together': {('supervisor', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='CouncilLiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_presentation', models.FloatField(default=0.0, help_text='Kỹ năng thuyết trình & Báo cáo')),
                ('score_content', models.FloatField(default=0.0, help_text='Chất lượng nội dung chuyên môn')),
                ('score_qa', models.FloatField(default=0.0, help_text='Trả lời câu hỏi phản biện')),
                ('score_demo', models.FloatField(default=0.0, help_text='Sản phẩm Demo / Ứng dụng')),
                ('total_score', models.FloatField(default=0.0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_scores', to='app.defensecouncil')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to='app.councilmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_scores', to='app.graduationproject')),
            ],
            options={
                'unique_together': {('project', 'member')},
            },
        ),
    ]
