# Generated by Django 4.2.30 on 2026-09-08 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_academicbatch_defensecouncil_graduationproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='academic_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_groups', to='app.academicbatch'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_recruiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='app.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='group',
            name='tentative_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='tentative_topic',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='group',
            name='topic_revision_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='topic_status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'Chưa đăng ký đề tài'), ('PENDING_REVIEW', 'Chờ duyệt đề tài'), ('REVISION_REQUESTED', 'Yêu cầu chỉnh sửa'), ('APPROVED', 'Đã phê duyệt chính thức'), ('REJECTED', 'Từ chối')], default='NOT_REGISTERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='project_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupmate_project', to='app.projectcategories'),
        ),
        migrations.AlterField(
            model_name='group',
            name='student_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_request', to='app.student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('group_request', 'Group Request'), ('group_request_accepted', 'Group Request Accepted'), ('group_request_rejected', 'Group Request Rejected'), ('group_join_request', 'Group Join Request'), ('group_kicked', 'Group Kicked'), ('group_leave', 'Group Leave'), ('group_disbanded', 'Group Disbanded'), ('group_leadership_transferred', 'Leadership Transferred'), ('topic_revision_resubmitted', 'Topic Revision Resubmitted'), ('supervisor_request', 'Supervisor Request'), ('supervisor_request_accepted', 'Supervisor Request Accepted'), ('supervisor_request_rejected', 'Supervisor Request Rejected'), ('new_chat_message', 'New Chat Message'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('evaluation_completed', 'Evaluation Completed'), ('new_comment', 'New Comment'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('ACCEPTED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_join_requests', to='app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Trưởng nhóm'), ('MEMBER', 'Thành viên')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='app.student')),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
    ]
