# Generated by Django 4.2.30 on 2026-09-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_academicbatch_defensecouncil_graduationproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionMeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.CharField(blank=True, default='09:00 - 10:30', max_length=100)),
                ('meeting_type', models.CharField(choices=[('OFFLINE', 'Gặp trực tiếp'), ('ONLINE', 'Trực tuyến (Meet/Zoom)')], default='OFFLINE', max_length=50)),
                ('location_or_link', models.CharField(blank=True, max_length=255, null=True)),
                ('content_discussed', models.TextField(help_text='Nội dung đã trao đổi, tiến độ công việc')),
                ('supervisor_notes', models.TextField(blank=True, help_text='Nhận xét / Góp ý của GVHD', null=True)),
                ('next_meeting_plan', models.TextField(blank=True, help_text='Kế hoạch và mục tiêu cho buổi gặp tiếp theo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='defensecouncil',
            name='current_defending_project',
            field=models.ForeignKey(blank=True, help_text='Đề tài / Sinh viên đang trên bục bảo vệ trực tiếp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_defense_councils', to='app.graduationproject'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='defense_status',
            field=models.CharField(choices=[('WAITING', 'Chờ bảo vệ'), ('DEFENDING', 'Đang bảo vệ'), ('DEFENDED', 'Đã bảo vệ')], default='WAITING', max_length=50),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='status',
            field=models.CharField(choices=[('ALLOCATED', 'Đã phân GVHD'), ('OUTLINE_PENDING', 'Chờ duyệt đề cương'), ('OUTLINE_REVISION', 'Yêu cầu sửa đề cương'), ('OUTLINE_APPROVED', 'Đề cương đã duyệt'), ('IN_PROGRESS', 'Đang thực hiện đồ án'), ('DEFENSE_READY', 'Đủ điều kiện bảo vệ'), ('DEFENDING', 'Đang bảo vệ'), ('PASSED', 'Bảo vệ thành công - Đạt'), ('FAILED', 'Không đạt'), ('DEFERRED', 'Bảo lưu đồ án')], default='ALLOCATED', max_length=50),
        ),
        migrations.CreateModel(
            name='SupervisionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn thành')], default='TODO', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True, help_text='Ghi chú, link commit hoặc báo cáo kết quả của SV', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='app.supervisor')),
                ('meeting_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='app.supervisionmeetinglog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.graduationproject')),
            ],
            options={
                'ordering': ['is_completed', 'due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supervisionmeetinglog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_logs', to='app.graduationproject'),
        ),
    ]
