# Generated by Django 4.2.30 on 2026-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_academicbatch_defensecouncil_graduationproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Đánh dấu bài nộp muộn sau deadline'),
        ),
        migrations.AddField(
            model_name='document',
            name='late_duration',
            field=models.CharField(blank=True, help_text='Thời gian nộp muộn (ví dụ: Trễ 2 giờ 15 phút)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='allow_late_submission',
            field=models.BooleanField(default=False, help_text='Cho phép sinh viên nộp sau deadline (nếu bật: nộp được và gắn nhãn Late; nếu tắt: khóa nộp)'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
