# Generated by Django 4.2.30 on 2026-09-08 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatroom_attachment_chatroom_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensecouncil',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Khóa điểm hội đồng'),
        ),
        migrations.AddField(
            model_name='defensecouncil',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defensecouncil',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_councils', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation3supervisor',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation4supervisor',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='reviewer_verdict',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Cho phép bảo vệ'), ('CONDITIONAL', 'Bảo vệ có điều kiện'), ('REJECTED', 'Không cho phép bảo vệ')], default='APPROVED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='supervisor_score_is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scopedocumentevaluationcriteria',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sddevaluationsupervisor',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='srsevaluationsupervisor',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='general', help_text='Mục nhận xét (general, format, content, requirements,...)', max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
