# Generated by Django 4.2.30 on 2026-09-07 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_supervisionmeetinglog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Báo lỗi hệ thống', max_length=255)),
                ('description', models.TextField(help_text='Mô tả chi tiết lỗi gặp phải')),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='bug_reports/')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã giải quyết'), ('CLOSED', 'Đã đóng')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo lỗi',
                'verbose_name_plural': 'Danh sách báo cáo lỗi',
                'ordering': ['-created_at'],
            },
        ),
    ]
