# Generated by Django 4.2.30 on 2026-09-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_group_academic_batch_group_group_name_and_more'),
        ('app', '0008_defensecouncil_is_locked_defensecouncil_locked_at_and_more'),
        ('app', '0008_systembugreport'),
    ]

    operations = [
    ]
