# Generated by Django 4.2.30 on 2026-09-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20260909_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('evaluation_update', 'Evaluation Update'), ('document_status_change', 'Document Status Change'), ('group_status_change', 'Group Status Change'), ('supervisor_request_update', 'Supervisor Request Update'), ('email_notification_error', 'Email Notification Error')], default='evaluation_update', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('committee_member', 'Committee Member'), ('external_examiner', 'External Examiner')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='topic_status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'Chưa đăng ký đề tài'), ('PENDING_REVIEW', 'Chờ duyệt đề tài'), ('REVISION_REQUESTED', 'Yêu cầu chỉnh sửa'), ('APPROVED', 'Đã phê duyệt chính thức'), ('REJECTED', 'Từ chối')], db_index=True, default='NOT_REGISTERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
