# Generated by Django 4.2.30 on 2026-10-05 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_auditlog_action_type_alter_auditlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='academic_clearance_status',
            field=models.CharField(choices=[('PENDING', 'Chờ kiểm tra'), ('CLEARED', 'Đạt điều kiện'), ('NOT_CLEARED', 'Chưa đạt')], default='CLEARED', max_length=20),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='is_force_approved',
            field=models.BooleanField(default=False, help_text='Khoa duyệt đặc cách cho làm ĐA'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='signed_outline_file',
            field=models.FileField(blank=True, null=True, upload_to='signed_outlines/'),
        ),
        migrations.AddField(
            model_name='internshipinfo',
            name='preference_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref1_students', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='internshipinfo',
            name='preference_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref2_students', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='internshipinfo',
            name='preference_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref3_students', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='internshipinfo',
            name='secondary_criteria_note',
            field=models.TextField(blank=True, help_text='Tiêu chí phụ / Định hướng công nghệ', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cpa',
            field=models.FloatField(default=0.0, help_text='Điểm trung bình tích lũy thang 4'),
        ),
        migrations.AddField(
            model_name='student',
            name='credits_accumulated',
            field=models.IntegerField(default=0, help_text='Số tín chỉ đã tích lũy'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree_program',
            field=models.CharField(choices=[('BACHELOR', 'Cử nhân'), ('ENGINEER', 'Kỹ sư')], default='BACHELOR', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='is_eligible_for_thesis',
            field=models.BooleanField(default=True, help_text='Đủ điều kiện làm ĐA'),
        ),
        migrations.AddField(
            model_name='supervisiontask',
            name='deliverable_file',
            field=models.FileField(blank=True, null=True, upload_to='task_deliverables/'),
        ),
        migrations.AddField(
            model_name='supervisiontask',
            name='deliverable_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supervisiontask',
            name='review_verdict',
            field=models.CharField(choices=[('PENDING', 'Chờ đánh giá'), ('ACCEPTED', 'Đạt'), ('REVISION_REQUIRED', 'Yêu cầu làm lại')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisiontask',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisiontask',
            name='supervisor_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='status',
            field=models.CharField(choices=[('ALLOCATED', 'Đã phân GVHD'), ('TOPIC_DRAFT', 'Đang xây dựng đề tài (Draft)'), ('TOPIC_CONFIRMED', 'GV đã xác nhận đề tài'), ('TOPIC_REVISION', 'Khoa yêu cầu sửa đề tài'), ('TOPIC_APPROVED', 'Đề tài đã duyệt'), ('ELIGIBILITY_CHECK_PENDING', 'Chờ xét điều kiện làm ĐA'), ('OUTLINE_PENDING', 'Chờ duyệt đề cương'), ('OUTLINE_REVISION', 'Yêu cầu sửa đề cương'), ('OUTLINE_APPROVED', 'Đề cương đã duyệt'), ('IN_PROGRESS', 'Đang thực hiện đồ án'), ('DEFENSE_READY', 'Đủ điều kiện bảo vệ'), ('DEFENDING', 'Đang bảo vệ'), ('PASSED', 'Bảo vệ thành công - Đạt'), ('FAILED', 'Không đạt'), ('DEFERRED', 'Bảo lưu đồ án'), ('DISQUALIFIED', 'Loại khỏi đợt đồ án')], default='ALLOCATED', max_length=50),
        ),
        migrations.CreateModel(
            name='ThesisDeferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Lý do xin bảo lưu đồ án')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='deferral_evidence/')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ Khoa duyệt'), ('APPROVED', 'Đã duyệt bảo lưu'), ('REJECTED', 'Không chấp nhận / Loại khỏi đợt')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferral_requests', to='app.graduationproject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deferral_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferral_requests', to='app.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_preference', models.IntegerField(default=1, help_text='Khớp NV1 (1), NV2 (2), NV3 (3) hoặc Hệ thống gán (0)')),
                ('match_score', models.FloatField(default=0.0)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_allocations', to='app.academicbatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_assignments', to='app.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_students', to='app.supervisor')),
            ],
            options={
                'ordering': ['student__registration_no'],
                'unique_together': {('batch', 'student')},
            },
        ),
    ]
