# Generated by Django 4.2.30 on 2026-10-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_graduationproject_academic_clearance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisiontask',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Đánh dấu nộp muộn so với deadline (Late Submit)'),
        ),
        migrations.AddField(
            model_name='supervisiontask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm sinh viên nộp bài', null=True),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='status',
            field=models.CharField(choices=[('ALLOCATED', 'Đã phân GVHD'), ('TOPIC_DRAFT', 'Đang xây dựng đề tài (Draft)'), ('TOPIC_CONFIRMED', 'GV đã xác nhận đề tài'), ('PENDING_REVIEW', 'Chờ duyệt đề tài'), ('TOPIC_REVISION', 'Khoa yêu cầu sửa đề tài'), ('TOPIC_APPROVED', 'Đề tài đã duyệt'), ('ELIGIBILITY_CHECK_PENDING', 'Chờ xét điều kiện làm ĐA'), ('OUTLINE_PENDING', 'Chờ duyệt đề cương'), ('OUTLINE_REVISION', 'Yêu cầu sửa đề cương'), ('OUTLINE_APPROVED', 'Đề cương đã duyệt'), ('IN_PROGRESS', 'Đang thực hiện đồ án'), ('DEFENSE_READY', 'Đủ điều kiện bảo vệ'), ('DEFENDING', 'Đang bảo vệ'), ('PASSED', 'Bảo vệ thành công - Đạt'), ('FAILED', 'Không đạt'), ('DEFERRED', 'Bảo lưu đồ án'), ('DISQUALIFIED', 'Loại khỏi đợt đồ án')], default='ALLOCATED', max_length=50),
        ),
    ]
